### ISSUE TITLE
Add IRR Summary

### ISSUE THREAD

**Issue by jkneifel** [usnistgov/E3#28]
IRR requires convergence calculations not yet build into E3.

**Comment by dw13813** [comment]
Write up for IRR
[Steps for Incremental IRR.docx](https://github.com/usnistgov/E3/files/7673641/Steps.for.Incremental.IRR.docx)

**Comment by dw13813** [comment]
Use same steps as IRR to recalculate costs/benefits to account for alternatives with no benefits then use steps for IRR relative to baseline from attached document above.

**Comment by dw13813** [comment]
IRR is fully functional
