### ISSUE TITLE
Sensitivity Debugging

### ISSUE THREAD

**Issue by dw13813** [usnistgov/E3#39]
Looks like an issue is causing a discrepancy between the expected output and what the code is outputting. Tasha, could you check that the code is only updating the BCN object being altered and not creating an entirely new one. My concern is that the code may be double counting a BCN. I'll also double check that my test is coded properly in case the issue is on my end.

**Comment by tashakim** [comment]
I'll look into this

**Comment by dw13813** [comment]
Sensitivity is functional
